// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6Assignment_cgp27.Models;

namespace Mission6Assignment_cgp27.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6Assignment_cgp27.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action",
                            Director = "Anthony and Joe Russo",
                            Edited = true,
                            Rating = "PG-13",
                            Title = "Avengers, Infinity War",
                            Year = 2018
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Fantasy",
                            Director = "Peter Jackson",
                            Edited = false,
                            LentTo = "Jacob",
                            Notes = "My Favorite Movie Ever",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = 2003
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Comedy",
                            Director = "Jared Hess",
                            Edited = false,
                            LentTo = "Rachel",
                            Notes = "Funniest Movie Ever",
                            Rating = "PG",
                            Title = "Napoleon Dynamite",
                            Year = 2004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
